--lab-4
--part A
SELECT *FROM DEPOSIT
--Add two more columns City VARCHAR (20) and Pincode INT FROM DEPOSIT TABLE
ALTER TABLE DEPOSIT ADD CITY VARCHAR(20),PINCODE INT 

--Change the size of CNAME column from VARCHAR (50) to VARCHAR (35)
ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35)

--Change the data type DECIMAL to INT in amount Column
ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT

--Rename Column ActNo to ANO
sp_rename 'DEPOSIT.ACTNO','ANO'

--Delete Column City from the DEPOSIT table.
ALTER TABLE DEPOSIT DROP COLUMN CITY 

--Change name of table DEPOSIT to DEPOSIT_DETAI
SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'

--PART-B
--Rename Column ADATE to AOPENDATE OF DEPOSIT_DETAIL table.
sp_rename 'DEPOSIT.ADATE','AOPENDATE'

--Delete Column AOPENDATE from the DEPOSIT_DETAIL table.
ALTER TABLE DEPOSIT DROP COLUMN AOPENDATE 

--Rename Column CNAME to CustomerName
sp_rename 'DEPOSIT.CNAME','CustomerName'

--PART-C(STUDENT)
--CREATE A STUDENT_DETAILS TABLE
SELECT NAME,CITY,AGE INTO STUDENT_DETAILS FROM EMPLOYEE_DETAIL
 SELECT*FROM EMPLOYEE_DETAIL WHERE 1=2

 CREATE TABLE STUDENT_DETAILED(
  ENROLLMENT_NO VARCHAR(20),
  NAME VARCHAR(25),
  CPI DECIMAL(5,2),
  BDATE DATETIME,
);
SP_RENAME 'STUDENT_DETAILED','STUDENTS_DETAIL'
INSERT INTO STUDENTS_DETAIL VALUES
(10120130112,'NOBITA','10',10-11-2003),
(20110230123,'DOREMON','9',07-02-2005),
(30140110313,'SUNIO','8',06-08-2004),
(40150120132,'GIAN','7',14-08-2004);
SELECT *FROM STUDENTS_DETAIL

--Add two more columns City VARCHAR (20) (Not null) and Backlog INT (Null).
ALTER TABLE STUDENTS_DETAIL ADD CITY VARCHAR(20) NOT NULL DEFAULT 'RAJKOT', BACKLOG INT;

--Change the size of NAME column of student_detail from VARCHAR (25) to VARCHAR (35).
ALTER TABLE STUDENTS_DETAILS ALTER COLUMN NAME VARCHAR(35)

--Change the data type DECIMAL to INT in CPI Column.
ALTER TABLE STUDENTS_DETAIL  ALTER COLUMN CPI INT

--Rename Column Enrollment_No to ENO.
sp_rename 'STUDENTS_DETAIL.ENROLLMENT_NO','ENO'

--Delete Column City from the student_detail table.
ALTER TABLE STUDENTS_DETAIL DROP COLUMN CITY 
--Change name of table student_detail to STUDENT_MASTER
sp_rename 'STUDENTS_DETAIL','STUDENT_MASTER'

SELECT *FROM STUDENT_MASTER