SELECT *FROM DEPOSIT
SELECT *FROM BORROW
SELECT *FROM CUSTOMERS
SELECT ACOUNTNO,CNAME,AMOUNT FROM DEPOSIT
SELECT LOANO,AMOUNT FROM BORROW
SELECT CNAME FROM CUSTOMERS WHERE CITY IN('NAGPUR','DELHI')
SELECT CNAME,BNAME FROM DEPOSIT WHERE AMOUNT>'4000' AND ACOUNTNO<105
SELECT CNAME FROM BORROW WHERE AMOUNT>='3000' AND AMOUNT<='8000'
SELECT ACOUNTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME in('AJNI','KAROL','M.G.ROAD')
--PART B
SELECT TOP 5* FROM DEPOSIT
SELECT TOP 3* FROM DEPOSIT WHERE AMOUNT>1000
SELECT TOP 5 LOANO,CNAME FROM BORROW WHERE BNAME<>'ANDHERI'
SELECT DISTINCT CITY FROM CUSTOMERS
SELECT DISTINCT BNAME FROM BRANCH
 --PART C
 SELECT TOP 25 PERCENT* FROM DEPOSIT WHERE AMOUNT>5000
 SELECT TOP 10 PERCENT* FROM BORROW WHERE AMOUNT >1000 
 SELECT *, AMOUNT+(AMOUNT*0.1) AS'EXTRA AMOUNT' FROM BORROW
 SELECT TOP 10 PERCENT AMOUNT FROM BORROW
 SELECT DISTINCT CNAME,CITY FROM CUSTOMERS
 SELECT LOANO FROM BORROW